### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Closes #3

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge/clsparse This PR is ready to go!

**Comment by beckermr** [comment]
@conda-forge/core This PR is ready to go.

**Comment by jakirkham** [comment]
@beckermr, we have to sort out the `OSX_VARIANT` stuff still. @isuruf was working on this for `pyopencl` in PR ( https://github.com/conda-forge/pyopencl-feedstock/pull/34 ). I think it is a matter for porting a similar PR over. It might be somewhat cleaner to do that in a new PR and then update the rebuild PR.

**Comment by beckermr** [comment]
Ahhh cool. Thanks!

**Comment by isuruf** [comment]
We switched over to using an ICD loader on all platforms now.
```
- khronos-opencl-icd-loader   # [win or osx]
- ocl-icd                               # [linux]
```
should give you an ocl loader.

`pocl, oclgrind` are 2 opencl implementations in conda-forge and `ocl_icd_wrapper_apple` just exposes the builtin opencl platform on osx.

**Comment by beckermr** [comment]
I am closing this PR as I do not plan to finish it. @conda-forge/clsparse for viz

**Pull request closed without merging**
